########################
# SPRING Configuration #
########################
spring:
  application:
    name: spring-boot-oidc-resource-server
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  # JMX
  jmx:
    enabled: false
  # AOP
  aop:
    proxy-target-class: true
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          #/uaa/oauth/token
          issuer-uri: http://localhost:8000

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: TRACE
    org.springframework.web.client: TRACE
    org.springframework.security: TRACE

### Server ###
server:
  port: 8080
  servlet:
    context-path: /api


feign:
  client:
    config:
      default:
        logger-level: full