
### Spring ###
spring:
  application:
    name: spring-boot-simple-jwt
  jackson:
    default-property-inclusion: NON_NULL

### Logging ###
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    no.acntech: DEBUG

### Server ###
server:
  port: 8081
  servlet:
    context-path: /api
